# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 710850fd0e23ad8dba9086586aafc48e46d80e63b3467408945603019a86c43bab703a83862f9d4d48ad6416ae286e849d335634146db0ef7aa88351b11f38fd

test:
  secret_key_base: b7919cbac46497b8a20689fc7dfdf154508082e7bf0bb24e96d3ab6172f597126b42d8e0fe94570efd79a126290950d865ef04c06b8182f8c72123c5c98011cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
